language: python

python:
  - "3.4"

install:
  # Note: requests must be installed before `python setup.py sdist install`.
  - pip install requests
  - python setup.py sdist install

script:
  # Note: Travis CI's virtualenv installs `nose`
  - nosetests
