language: python

python:
  - "3.4"

install:
  # Note: On Travis-CI, requests must be installed before `python setup.py sdist install`.
  - pip install requests
  - pip install coveralls
  - python setup.py sdist install

script:
  # Note: Travis CI's virtualenv pre-installs `nose`
  # https://github.com/coagulant/coveralls-python#nosetests
  - nosetests  --with-coverage --cover-package=cltk

# https://github.com/coagulant/coveralls-python#usage-travis-ci
after_success:
 - coveralls
