sudo: required  # install TLGU w/o sudo and then use `false`

language: python

python:
  - "3.4"
  - "3.5"

install:
  # openblas req'd for numpy
  - sudo apt-get install -y libblas-dev liblapack-dev
  - pip install gensim
  - python setup.py sdist install

before_script:
  - pip install codecov
  - pip install coveralls

script:
  # Notes on nose:
  # Travis CI pre-installs `nose`
  # https://github.com/coagulant/coveralls-python#nosetests
  # http://nose.readthedocs.org/en/latest/plugins/skip.html
  - nosetests --no-skip --with-coverage --cover-package=cltk

after_success:
  - codecov
  # Notes on Coveralls
  # https://github.com/coagulant/coveralls-python#usage-travis-ci
  - coveralls
